// Code generated by hand; for testing purposes only.

package search

import (
	"context"
	"fmt"
	"sync"
)

// MockEngine 搜索引擎的模拟实现，用于单元测试。
// 通过设置各行为的返回值和回调来验证调用方行为。
type MockEngine struct {
	mu sync.Mutex

	// 记录调用
	IndexCalls  []IndexCall
	DeleteCalls []DeleteCall
	SearchCalls []SearchCall

	// 控制返回值
	IndexFunc  func(docs ...Document) error
	DeleteFunc func(ids ...string) error
	SearchFunc func(q *Query) (*SearchResponse, error)
	ClearErr   error
	CloseErr   error
	Available  bool
}

type IndexCall struct {
	Documents []Document
}

type DeleteCall struct {
	IDs []string
}

type SearchCall struct {
	Query *Query
}

func NewMockEngine() *MockEngine {
	return &MockEngine{
		Available: true,
	}
}

func (m *MockEngine) Index(_ context.Context, docs ...Document) error {
	m.mu.Lock()
	m.IndexCalls = append(m.IndexCalls, IndexCall{Documents: docs})
	m.mu.Unlock()
	if m.IndexFunc != nil {
		return m.IndexFunc(docs...)
	}
	return nil
}

func (m *MockEngine) Delete(_ context.Context, ids ...string) error {
	m.mu.Lock()
	m.DeleteCalls = append(m.DeleteCalls, DeleteCall{IDs: ids})
	m.mu.Unlock()
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ids...)
	}
	return nil
}

func (m *MockEngine) Search(_ context.Context, q *Query) (*SearchResponse, error) {
	m.mu.Lock()
	m.SearchCalls = append(m.SearchCalls, SearchCall{Query: q})
	m.mu.Unlock()
	if m.SearchFunc != nil {
		return m.SearchFunc(q)
	}
	return &SearchResponse{
		Results:  []SearchResult{},
		Total:    0,
		Page:     1,
		PageSize: 20,
	}, nil
}

func (m *MockEngine) ClearIndex(_ context.Context) error {
	return m.ClearErr
}

func (m *MockEngine) Close() error {
	return m.CloseErr
}

func (m *MockEngine) IsAvailable() bool {
	return m.Available
}

// Reset 清空调用记录
func (m *MockEngine) Reset() {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.IndexCalls = nil
	m.DeleteCalls = nil
	m.SearchCalls = nil
}

func (m *MockEngine) String() string {
	return fmt.Sprintf("MockEngine{Index:%d, Delete:%d, Search:%d}",
		len(m.IndexCalls), len(m.DeleteCalls), len(m.SearchCalls))
}